# Generated by Django 4.1.5 on 2023-01-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('spendTime', models.IntegerField()),
                ('reviews', models.IntegerField()),
            ],
        ),
    ]
